export const ADD_MESSAGE_ACTION = 'ADD_MESSAGE';
export const SEND_MESSAGE_ACTION = 'SEND_MESSAGE';
export const REMOVE_MESSAGE_ACTION = 'REMOVE_MESSAGE';

export const LOAD_MESSAGES_PENDING_ACTION = 'LOAD_MESSAGES_PENDING';
export const LOAD_MESSAGES_SUCCESS_ACTION = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR_ACTION = 'LOAD_MESSAGES_ERROR';
export const SEND_FIREBASE_MESSAGE = 'SEND_FIREBASE_MESSAGE';

export const LOAD_MESSAGES_PENDING = 'LOAD_MESSAGES_PENDING';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';

export const UPDATE_CHAT_COLOR = 'UPDATE_CHAT_COLOR';
